language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo sh -c "echo \"deb http://debian.datastax.com/community stable main\" > /etc/apt/sources.list"
  - wget -O - http://debian.datastax.com/debian/repo_key | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install dsc
  - sudo /etc/init.d/cassandra start
install: pip install . --use-mirrors
script: nosetests
